### ISSUE TITLE
"xmpp.buddycloud.affiliation" stopped working

### ISSUE THREAD

**Issue by robotnic** [xmpp-ftw/xmpp-ftw-buddycloud#33]
Old version:

request
-----

3:::{"type":0,"data":["xmpp.buddycloud.affiliation",{"node":"/user/bill@laos.buddycloud.com/posts","jid":"robotnic@laos.buddycloud.com","affiliation":"member"}],"id":14}

result
---
3:::{"id":14,"type":1,"data":[null,true]}

new version
--------------
no result,
expected result: 3:::{"id":14,"type":1,"data":[null,true]}

**Comment by lloydwatkin** [comment]
Hey @robotnic tests aren't showing this, could you add some debug in `node_modules/xmpp-ftw-pubsub/lib/pubsub.js` on lines 494 and 496 to ensure that the event is being called and data is being returned please?

**Comment by robotnic** [comment]
I was using the xmpp-ftw of wifi-chat. There is no xmpp-ftw-pubsub. 

Working setup:
---------------------
xmpp-ftw-demo
remove line 82 in index.js (fanout)
use old primus.js, the new one starts with polling and has CORS problems.

**Comment by lloydwatkin** [comment]
There is xmpp-ftw-pubsub under wifi chat ;)

Also since its an IQ request I can't see how the fanout module is causing issues.

**Comment by robotnic** [comment]
https://github.com/project-isizwe/wifi-chat/blob/master/package.json

I don't see xmpp-ftw-pubsub.

fanout 
--------------
If fanout is active
"xmpp.pubsub.push.affiliation"

If fanout is not active
"xmpp.buddycloud.push.affiliation"

Should I check for both events?

**Comment by lloydwatkin** [comment]
Ahh right, push events :)  
Yes it may be that the fanout plugin hijacks these.

xmpp-ftw-pubsub is a sub-module of xmpp-ftw-buddycloud in wifi chat.

**Comment by robotnic** [comment]
Is it a bug or a feature?

**Comment by lloydwatkin** [comment]
Neither, since `xmpp-ftw-fanout` is only really designed to be used on its own. Ideally it shouldn't be intercepting these packets though. Could you raise an issue there and I'll pick it up as I have time. Cheers.
